- name: Dotfiles installation
  hosts: local
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.asdf/shims:{{ ansible_env.HOME }}/.asdf/bin"
  roles:
    - role: system_packages
      tags: system_packages
    - role: oh_my_bash
      tags: oh_my_bash
    - role: asdf
      tags: asdf
    - role: spacevim
      tags: spacevim
    - role: molecule
      tags: molecule
    - role: mitogen
      tags: mitogen
    - role: docker
      tags: docker
    - role: podman
      tags: podman
