- name: asdf dependencies installation
  become: yes
  package:
    name:
      - curl
      - git
    state: present

- name: fetch tags from asdf repository
  shell:
    cmd: curl --silent 'https://api.github.com/repos/asdf-vm/asdf/tags'
  register: asdf_tags_response
  args:
    warn: no  

- name: asdf installation
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: $HOME/.asdf
    version: "{{ asdf_tags_response.stdout | regex_search('v\\d+\\.\\d+\\.\\d+') }}"

- name: add asdf to bashrc
  lineinfile:
    path: $HOME/.bashrc
    line: "{{ item }}"
    state: present
  loop:
    - ". $HOME/.asdf/asdf.sh"
    - ". $HOME/.asdf/completions/asdf.bash"
    - "OSH_THEME='agnoster'"
