- name: fetch tags from asdf repository
  shell: curl --silent -u $GITHUB_USERNAME:$GITHUB_PASSWORD 'https://api.github.com/repos/asdf-vm/asdf/tags'
  register: asdf_tags_response
  args:
    warn: false
  changed_when: false

- name: asdf installation
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ ansible_env.HOME  }}/.asdf"
    version: "{{ asdf_tags_response.stdout | regex_search('v\\d+\\.\\d+\\.\\d+') }}"

- name: add asdf to bashrc
  lineinfile:
    path: "{{ ansible_env.HOME  }}/.bashrc"
    line: "{{ item }}"
    state: present
  loop:
    - ". {{ ansible_env.HOME  }}/.asdf/asdf.sh"
    - ". {{ ansible_env.HOME  }}/.asdf/completions/asdf.bash"
    # - "OSH_THEME='agnoster'"

- name: add asdf plugins
  shell: |
    source {{ ansible_env.HOME  }}/.asdf/asdf.sh && \
    (asdf list {{ item }} || asdf plugin-add {{ item }})
  args:
    executable: /bin/bash
  loop: "{{ asdf_plugins }}"

- name: install latest plugin packages
  shell: |
    source $HOME/.asdf/asdf.sh && \
    asdf install {{ item }} latest
  args:
    executable: /bin/bash
  loop: "{{ asdf_plugins }}"

- name: enable global plugin packages
  shell: |
    source $HOME/.asdf/asdf.sh && \
    asdf global {{ item }} latest
  args:
    executable: /bin/bash
  loop: "{{ asdf_plugins }}"
