- name: fetch tags from asdf repository
  shell: curl --silent 'https://api.github.com/repos/asdf-vm/asdf/tags'
  register: asdf_tags_response
  args:
    warn: no  

- name: asdf installation
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: $HOME/.asdf
    version: "{{ asdf_tags_response.stdout | regex_search('v\\d+\\.\\d+\\.\\d+') }}"

- name: add asdf to bashrc
  lineinfile:
    path: $HOME/.bashrc
    line: "{{ item }}"
    state: present
  loop:
    - ". $HOME/.asdf/asdf.sh"
    - ". $HOME/.asdf/completions/asdf.bash"
    - "OSH_THEME='agnoster'"

- name: install asdf plugins
  shell: asdf list {{ item }} ||  asdf plugin-add {{ item }}
  loop: "{{ asdf_plugins }}"

- name: install asdf plugins packages
  shell: asdf install {{ item }} latest
  loop: "{{ asdf_plugins }}"

- name: enable global asdf packages
  shell: |
    asdf current {{ item }} || asdf global {{ item }} latest
  loop: "{{ asdf_plugins }}"
